name: Futurehit
version: '${project.version}'
main: com.rowisabeast.futurehit.Futurehit
api-version: 1.18
authors: [ Row ]
description: Custom Plugin for Futurehit
website: https://rowisabeast.com

commands:
  bdussy:
    usage: /bdussy
    description: start prodection time
  donate:
    usage: /donate
    description: Donate to Row